eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   # 服务注册，默认为true，表示将自己注册到Eureka Server
    fetchRegistry: false       # 服务发现，默认为true，表示从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server